// https://nuxt.com/docs/api/configuration/nuxt-config
import { execSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

import pkg from './package.json'

// Fidelity has no backend (ADR-007). Directory layout per CLAUDE.md:
//   app/     Nuxt — pages, components, composables. Presentation only.
//   worker/  discogs, match, horizon. All the actual work.
//   db/      IndexedDB schema and access via idb.
//   shared/  types and the main ↔ worker postMessage protocol.
/**
 * The one description that reaches a link preview.
 *
 * English and one string, for the same reason the manifest is: this is read
 * before any of the app's code runs, so it cannot follow the language switch.
 * It says what the app does rather than what it is called — "Fidelity" alone
 * tells a person nothing about why the link is worth opening.
 */
/**
 * Root or subdirectory — one value, five effects.
 *
 * Nuxt reads `NUXT_APP_BASE_URL` of its own accord for `app.baseURL`. What it
 * does *not* do of its own accord is carry the manifest and the service worker
 * along: their `start_url`, `scope` and `navigateFallback` stayed at "/", and a
 * PWA with the wrong scope installs itself to the wrong address.
 *
 * Measured 2026-08-11 against a build for martinmelcher.de/fidelity: without
 * this, the finished page looks for its own files under /_nuxt/ — in the root
 * of somebody else's website — and stays blank.
 *
 * Left empty it is "/", which is exactly what Docker and the release zip
 * expect. The subpath is the exception, not the rule.
 */
const base = process.env.NUXT_APP_BASE_URL ?? '/'

const SHARE = {
  title: 'Fidelity — the clerk behind the counter, for Discogs',
  description:
    'Scan a Discogs shop and get back a scored list of the records in it that fit your collection — each one with a sentence saying why. Runs entirely in your browser.',
} as const

export default defineNuxtConfig({
  compatibilityDate: '2026-08-09',

  devtools: { enabled: true },

  // No server at runtime. `nuxt generate` writes .output/public and that is
  // the whole deployment: a docroot, Cloudflare Pages, GitHub Pages.
  ssr: false,

  nitro: {
    preset: 'static',
    prerender: {
      // The shell only. Every route is resolved client-side; unknown paths
      // fall back to 200.html.
      routes: ['/'],
    },
  },

  // Nuxt UI 4 brings Tailwind 4 and registers @tailwindcss/vite itself — the
  // Vite plugin route, not PostCSS (docs/01-ARCHITECTURE.md §4.4).
  modules: ['@nuxt/ui', '@nuxt/eslint', '@vite-pwa/nuxt'],

  css: ['~/assets/css/fonts.css', '~/assets/css/main.css'],

  /*
   * Three faces, out of this repository.
   *
   * `@nuxt/fonts` is gone, and with it the last thing this project fetched
   * from somebody else while the build ran. Google rotates its file addresses
   * without notice: four release builds died on a 404 from fonts.gstatic.com
   * across two days, none of them caused by a line in this repository, each
   * costing another attempt.
   *
   * `app/assets/css/fonts.css` and the woff2 files beside it are generated by
   * `scripts/fonts/vendor.mjs` from a build that still had the module. They
   * are byte-identical to what shipped, `unicode-range` and metric-override
   * fallbacks included — this changed where the fonts come from and nothing
   * about what arrives.
   *
   * To change a weight: turn a provider back on, build, run the script, turn
   * it off again. Rare enough to be worth the four minutes, and the
   * alternative is a release that depends on a third party answering
   * consistently.
   */
  fonts: {
    /*
     * Every remote provider off.
     *
     * `@nuxt/fonts` arrives with `@nuxt/ui` and cannot simply be removed, and
     * left alone it goes looking: it reads the `font-family` names out of the
     * CSS and fetches whatever it recognises. Switching the providers off is
     * what makes that impossible rather than merely unnecessary — including
     * for a family somebody adds later without thinking about builds.
     */
    providers: {
      google: false,
      fontshare: false,
      bunny: false,
      fontsource: false,
      googleicons: false,
      adobe: false,
    },
  },

  app: {
    baseURL: base,

    head: {
      /*
       * A title that is already in the HTML as delivered.
       *
       * There was none: the title was set at runtime only, and the prerendered
       * HTML carried no `<title>` at all — measured on 2026-08-11 against the
       * local build *and* against the deployed page. Two things read exactly
       * that static HTML: "Add to Home Screen", and every link preview.
       *
       * It says the bare name, and that is the whole point of it. Safari names
       * an installed icon from this, and the tagline it used to say became an
       * app called "Fidelity — the clerk behind the counter, for Discogs" on
       * somebody's phone. The tagline still reaches link previews through
       * og:title and twitter:title below, where a sentence belongs.
       *
       * Pages override it at runtime; this is the state before one does.
       */
      title: 'Fidelity',

      meta: [
        // Nothing here is meant for a search index (docs/00 §9). robots.txt
        // asks politely; this is the part crawlers actually honour.
        { name: 'robots', content: 'noindex, nofollow' },

        /*
         * The card a link turns into when somebody pastes it.
         *
         * On the shell rather than per page, and that is not laziness: with
         * `ssr: false` every address serves this one index.html. Whatever a
         * chat client, a messenger or a link preview fetches, it gets exactly
         * these tags — the per-page titles below are written by the app after
         * the page has already been fetched, which no unfurler waits for.
         *
         * So this describes the app, and the document title describes the
         * screen. Two different jobs that look like one.
         */
        { name: 'description', content: SHARE.description },
        { property: 'og:type', content: 'website' },
        { property: 'og:site_name', content: 'Fidelity' },
        { property: 'og:title', content: SHARE.title },
        { property: 'og:description', content: SHARE.description },
        { property: 'og:image', content: '/icons/icon-512.png' },
        { name: 'twitter:card', content: 'summary' },
        { name: 'twitter:title', content: SHARE.title },
        { name: 'twitter:description', content: SHARE.description },

        /*
         * Without these two, the address bar stays put.
         *
         * Measured 2026-08-11 against the deployed page: the HTML carried *no*
         * reference to the manifest — @vite-pwa creates the file, but with
         * `ssr: false` the `<link>` never lands in the pre-rendered HTML. So
         * iOS never finds the manifest, falls back to its old behaviour, and
         * `display: standalone` is never read.
         *
         * `apple-mobile-web-app-capable` is the old name and the one iOS still
         * listens to; `mobile-web-app-capable` is today's. Both, because each
         * without the other does nothing on one platform or the other.
         */
        /*
         * What the icon on a home screen is called.
         *
         * iOS asks this first and falls back to the document title, which is
         * how somebody ended up with an app called "Willkommen · Fidelity".
         * The manifest says the same thing for everyone else; this is the one
         * Safari reads.
         */
        { name: 'apple-mobile-web-app-title', content: 'Fidelity' },
        { name: 'apple-mobile-web-app-capable', content: 'yes' },
        { name: 'mobile-web-app-capable', content: 'yes' },

        // The status bar above the app: translucent, so the app's dark
        // background runs up under the clock instead of ending at a white
        // strip.
        { name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent' },
      ],

      /*
       * Everything "add to home screen" reads has to be **here**.
       *
       * These references lived in app.vue, so inside a `useHead` — which runs
       * on hydration and never lands in the pre-rendered HTML. For adding,
       * Safari reads precisely that static HTML: it found no manifest and no
       * icon, took the page title ("Welcome · Fidelity") and drew a W in a
       * black square.
       *
       * And all three with the base path. Without it, `/icons/…` under
       * /fidelity/ points at the domain root — measured: 404 there, 200 with
       * the path.
       */
      link: [
        { rel: 'manifest', href: `${base}manifest.webmanifest` },
        { rel: 'icon', type: 'image/svg+xml', href: `${base}icon.svg` },
        { rel: 'apple-touch-icon', href: `${base}icons/apple-touch-icon.png` },
      ],
    },
  },

  pwa: {
    // Never 'autoUpdate'. A silent skipWaiting would swap the code out from
    // under a running dig — four minutes of scanning, gone. The user gets
    // asked, and the answer can be "later".
    registerType: 'prompt',
    manifest: {
      name: 'Fidelity',
      short_name: 'Fidelity',
      /*
       * The manifest is read once at install time, by the operating system,
       * before any of the app's own code runs. It cannot follow the language
       * switch, so it says English — the base language (ADR-010) — and stays
       * one string in one language on purpose.
       */
      description: 'The clerk behind the counter — for Discogs.',
      lang: 'en',
      start_url: base,
      scope: base,
      display: 'standalone',
      // The neutral ramp's darkest step: the shell must not flash white while
      // the app boots on a phone.
      background_color: '#0a0908',
      theme_color: '#0a0908',
      icons: [
        { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
        { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
        {
          src: '/icons/icon-maskable-512.png',
          sizes: '512x512',
          type: 'image/png',
          purpose: 'maskable',
        },
      ],
    },
    /*
     * The worker is written, not generated — `app/sw/sw.ts`.
     *
     * `generateSW` can only build a worker out of the vocabulary this config
     * has, and push is not in it: a notification arrives when no tab is open,
     * and only code inside the worker can answer that. So the build injects
     * the file list into a worker of ours instead of writing one.
     *
     * Everything that used to stand here — the navigation fallback and the
     * cover cache — is now three `registerRoute` calls in that file, where the
     * comments explaining them live too.
     */
    strategies: 'injectManifest',
    // Relative to Nuxt's srcDir, which is `app/`. Spelling it `app/sw` here
    // resolves to `app/app/sw` and the build stops without a hint as to why.
    srcDir: 'sw',
    filename: 'sw.ts',
    injectManifest: {
      globPatterns: ['**/*.{js,css,html,svg,png,woff2}'],
    },
    client: {
      /*
       * Explicitly `true`, and that is not decoration.
       *
       * The module sets its defaults like this:
       *
       *     const client = options.client ?? { registerPlugin: true, … }
       *     if (client.registerPlugin) addPlugin(…)
       *
       * So the default object only applies when `client` is missing
       * **entirely**. If even a single other key is here — `installPrompt`,
       * say — `registerPlugin` is `undefined`, and the plugin that registers
       * the service worker is never added.
       *
       * With `generateSW` this does not show: there, vite-plugin-pwa injects
       * the registration into the HTML as well, and that one works. Switching
       * to `injectManifest` left only this path — and the app had no service
       * worker: built, deployed, registered by nobody. Measured: one
       * registration before, zero after.
       */
      registerPlugin: true,
      // The install prompt is handled in the UI, not by the module: iOS has no
      // beforeinstallprompt at all and needs a coach mark instead (M6).
      installPrompt: false,
    },
    devOptions: {
      // A service worker in dev caches the very thing being edited.
      enabled: false,
    },
  },

  vite: {
    server: {
      /*
       * Vite rejects requests whose Host header it does not recognise, which is
       * right — it stops DNS rebinding against a dev server. A Cloudflare quick
       * tunnel arrives as `<something>.trycloudflare.com`, so that one suffix is
       * allowed explicitly rather than the check being switched off.
       *
       * Dev only: `nuxt generate` produces static files and has no server.
       */
      allowedHosts: ['.trycloudflare.com'],
    },

    worker: {
      // Without this Vite bundles the whole worker into one file and the
      // dynamic imports in worker/handlers.ts split into nothing. The basket
      // and the detail sheet are not needed to run a dig, and a dig is the
      // thing somebody actually waits for (docs/12 §2).
      format: 'es',
    },
  },

  typescript: {
    strict: true,
    // Type checking runs as its own job (`pnpm typecheck`), not inside dev/build.
    typeCheck: false,
  },

  runtimeConfig: {
    public: {
      // Bumped by release-please, shown in the footer.
      version: pkg.version,
      /*
       * Which build exactly, next to the version.
       *
       * The version alone cannot answer "is this the code I just deployed" —
       * it only moves when a release is cut, and a service worker can serve a
       * shell from before that for as long as somebody taps "Später". Seven
       * characters settle it.
       *
       * Falls back to empty rather than failing: `git` is not there in every
       * build environment, and a missing commit hash is not worth a broken
       * build.
       */
      commit: buildCommit(),
      /**
       * What is new in this release — for people, not for machines.
       *
       * Read from `CHANGELOG.md`, but only an entry's **hand-written lead**:
       * the paragraph between the version heading and the first `###`. The
       * commit lists below it are written for the repository — "fix(deploy):
       * the hub check checked nothing" says precisely nothing to somebody
       * using the app.
       *
       * The whole file would be the wrong way to do this: 47 kB, three
       * quarters of it lines nobody wants to read. This way it is one or two.
       */
      releaseNotes: releaseNotes(pkg.version),
    },
  },
})

/**
 * The lead of this version's entry, or an empty string.
 *
 * Empty is not a fault in the build but one in the release: a test holds that
 * the version in `package.json` has a lead. That is where a release with not
 * one word to anybody shows up — in the release PR, while it can still be
 * written.
 */
function releaseNotes(version: string): string {
  let text: string
  try {
    text = readFileSync(new URL('./CHANGELOG.md', import.meta.url), 'utf8')
  } catch {
    return ''
  }

  // This version's heading — linked or not, both occur.
  const start = text.search(new RegExp(`^## \\[?${version.replace(/\./g, '\\.')}[\\](]`, 'm'))
  if (start === -1) return ''

  const rest = text.slice(start)
  const afterHeading = rest.indexOf('\n') + 1
  // Up to the first section or the next version, whichever comes first — an
  // entry with no lead should come out empty rather than taking the commit
  // list with it.
  const end = rest.slice(afterHeading).search(/^(###? )/m)

  return rest.slice(afterHeading, end === -1 ? undefined : afterHeading + end).trim()
}

function buildCommit(): string {
  if (process.env.GITHUB_SHA) return process.env.GITHUB_SHA.slice(0, 7)
  try {
    return execSync('git rev-parse --short=7 HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
  } catch {
    return ''
  }
}
